backend:
  name: github
  repo: 187370/187370.github.io
  branch: source
  squash_merges: true

# 禁用 Netlify 的身份验证服务
# publish_mode: editorial_workflow
site_url: https://pku-cs-cjw.top
display_url: https://pku-cs-cjw.top

# 媒体文件配置
media_folder: "source/images/uploads"
public_folder: "/images/uploads"

# 国际化
locale: 'zh_Hans'

# 集合配置
collections:
  - name: "posts"
    label: "博客文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false }
      - { 
          label: "标签", 
          name: "tags", 
          widget: "select",
          multiple: true,
          options: ["笔记", "CSAPP", "ics", "数算", "教程", "水文", "数据结构与算法A"],
          required: false
        }
      - { 
          label: "分类", 
          name: "categories", 
          widget: "select",
          options: ["学习笔记", "大学生涯", "日常生活"],
          required: false
        }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - { label: "摘要", name: "description", widget: "text", required: false }
      - { label: "是否置顶", name: "sticky", widget: "boolean", default: false, required: false }
      - { label: "数学公式", name: "mathjax", widget: "boolean", default: false, required: false }
      - { label: "正文", name: "body", widget: "markdown" }

# 预览模式
show_preview_links: true

# 编辑器工具栏配置
editor:
  preview: true